name: flutter_floripa_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slides: 0.0.9
  flutter_beat_sequencer:
    git: https://github.com/modulovalue/flutter_beat_sequencer
  vr_landing:
    git: https://github.com/roberto198907/flutterweb_landingpage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/logovr.png
    - assets/play.png
    - assets/vrilustration.png
